### ISSUE TITLE
有时候测试会出这个问题

### ISSUE THREAD

**Issue by Chyroc** [Chyroc/WechatSogou#122]
```
test_get_gzh_artilce_by_history_real (test.test_api.TestAPIReal) ... ERROR
test_get_gzh_artilce_by_hot_real (test.test_api.TestAPIReal) ... ERROR
test_get_sugg (test.test_api.TestAPIReal) ... ok
test_search_gzh_real (test.test_api.TestAPIReal) ... ERROR
test_const_hot_index (test.test_const.TestConst) ... ok
test_const_search_article_time (test.test_const.TestConst) ... ok
test_const_search_article_type (test.test_const.TestConst) ... ok
test_gen_hot_url (test.test_request_gen_hot_url.TestBasicGenSearchArticleURL) ... ok
test_gen_search_article_url_article_type (test.test_request_gen_search_article_url.TestBasicGenSearchArticleURL) ... ok
test_gen_search_article_url_keyword (test.test_request_gen_search_article_url.TestBasicGenSearchArticleURL) ... ok
test_gen_search_article_url_page (test.test_request_gen_search_article_url.TestBasicGenSearchArticleURL) ... ok
test_gen_search_article_url_timesn (test.test_request_gen_search_article_url.TestBasicGenSearchArticleURL) ... ok
test_gen_search_article_url_keyword (test.test_request_gen_search_gzh_url.TestBasicGenSearchGzhURL) ... ok
test_gen_search_gzh_url_page (test.test_request_gen_search_gzh_url.TestBasicGenSearchGzhURL) ... ok
test_get_article_by_history_json (test.test_structuring.TestStructuringGzh) ... ok
test_get_article_by_search (test.test_structuring.TestStructuringGzh) ... ok
test_get_gzh_artilce_by_hot (test.test_structuring.TestStructuringGzh) ... ok
test_get_gzh_by_search (test.test_structuring.TestStructuringGzh) ... ok
test_get_gzh_info_and_article_by_history (test.test_structuring.TestStructuringGzh) ... ok
test_get_gzh_info_by_history (test.test_structuring.TestStructuringGzh) ... ok
test_get_elem_text (test.test_tools.TestTools) ... ok
test_get_url_param (test.test_tools.TestTools) ... ok
test_list_or_empty (test.test_tools.TestTools) ... ok
test_replace_html (test.test_tools.TestTools) ... ok
test_replace_space (test.test_tools.TestTools) ... ok
test_str_to_dict (test.test_tools.TestTools) ... ok

======================================================================
ERROR: test_get_gzh_artilce_by_history_real (test.test_api.TestAPIReal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chyroc/Code/Chyroc/WechatSogou/test/test_api.py", line 35, in test_get_gzh_artilce_by_history_real
    identify_image_callback_weixin=self.identify_image_callback_ruokuai_weixin)
  File "/Users/chyroc/Code/Chyroc/WechatSogou/wechatsogou/api.py", line 315, in get_gzh_artilce_by_history
    gzh_list = self.get_gzh_info(keyword, unlock_callback_sogou, identify_image_callback_sogou)
  File "/Users/chyroc/Code/Chyroc/WechatSogou/wechatsogou/api.py", line 135, in get_gzh_info
    info = self.search_gzh(wecgat_id_or_name, 1, unlock_callback, identify_image_callback)
  File "/Users/chyroc/Code/Chyroc/WechatSogou/wechatsogou/api.py", line 182, in search_gzh
    identify_image_callback=identify_image_callback)
  File "/Users/chyroc/Code/Chyroc/WechatSogou/wechatsogou/api.py", line 92, in __get_by_unlock
    resp = self.__get(url, session, headers=self.__set_cookie(referer=referer))
  File "/Users/chyroc/Code/Chyroc/WechatSogou/wechatsogou/api.py", line 30, in __set_cookie
    suv = ws_cache.get('suv') if suv is None else suv
  File "/Users/chyroc/Code/Chyroc/WechatSogou/.tox/py27/lib/python2.7/site-packages/werkzeug/contrib/cache.py", line 753, in get
    return pickle.load(f)
ValueError: unsupported pickle protocol: 4

======================================================================
ERROR: test_get_gzh_artilce_by_hot_real (test.test_api.TestAPIReal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chyroc/Code/Chyroc/WechatSogou/test/test_api.py", line 43, in test_get_gzh_artilce_by_hot_real
    identify_image_callback=self.identify_image_callback_sogou)
  File "/Users/chyroc/Code/Chyroc/WechatSogou/wechatsogou/api.py", line 365, in get_gzh_artilce_by_hot
    identify_image_callback=identify_image_callback)
  File "/Users/chyroc/Code/Chyroc/WechatSogou/wechatsogou/api.py", line 92, in __get_by_unlock
    resp = self.__get(url, session, headers=self.__set_cookie(referer=referer))
  File "/Users/chyroc/Code/Chyroc/WechatSogou/wechatsogou/api.py", line 30, in __set_cookie
    suv = ws_cache.get('suv') if suv is None else suv
  File "/Users/chyroc/Code/Chyroc/WechatSogou/.tox/py27/lib/python2.7/site-packages/werkzeug/contrib/cache.py", line 753, in get
    return pickle.load(f)
ValueError: unsupported pickle protocol: 4

======================================================================
ERROR: test_search_gzh_real (test.test_api.TestAPIReal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chyroc/Code/Chyroc/WechatSogou/test/test_api.py", line 28, in test_search_gzh_real
    gzh_list = ws_api.search_gzh(gaokao_keyword, identify_image_callback=self.identify_image_callback_sogou)
  File "/Users/chyroc/Code/Chyroc/WechatSogou/wechatsogou/api.py", line 182, in search_gzh
    identify_image_callback=identify_image_callback)
  File "/Users/chyroc/Code/Chyroc/WechatSogou/wechatsogou/api.py", line 92, in __get_by_unlock
    resp = self.__get(url, session, headers=self.__set_cookie(referer=referer))
  File "/Users/chyroc/Code/Chyroc/WechatSogou/wechatsogou/api.py", line 30, in __set_cookie
    suv = ws_cache.get('suv') if suv is None else suv
  File "/Users/chyroc/Code/Chyroc/WechatSogou/.tox/py27/lib/python2.7/site-packages/werkzeug/contrib/cache.py", line 753, in get
    return pickle.load(f)
ValueError: unsupported pickle protocol: 4

----------------------------------------------------------------------
Ran 26 tests in 0.509s

FAILED (errors=3)
ERROR: InvocationError: '/Users/chyroc/Code/Chyroc/WechatSogou/.tox/py27/bin/python -m nose -vs'
```

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video

**Comment by Chyroc** [comment]
python 2和3切换的时候，读缓存出现协议不兼容的问题，已经修复
