### ISSUE TITLE
你这个 Readme 里面，大小写不分的啊

### ISSUE THREAD

**Issue by iiiyu** [Chyroc/WechatSogou#159]
WechatSogouAPI

**Comment by iiiyu** [comment]
大哥，每次看你这文档。我都没本事 run 起来。 
```
Python 3.6.3 (default, Oct  4 2017, 23:46:27)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import wechatsogou
>>> ws_api = wechatsogou.WechatSogouApi()
>>> ws_api.get_gzh_info('南航青年志愿者')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/iYu/Developer/Github/WechatSogou/wechatsogou/api.py", line 101, in get_gzh_info
    info = self.search_gzh_info(wechatid, 1)
  File "/Users/iYu/Developer/Github/WechatSogou/wechatsogou/api.py", line 58, in search_gzh_info
    if "authnamewrite" in cache_re[2]:
IndexError: list index out of range
>>>
```

**Comment by Chyroc** [comment]
![image](https://user-images.githubusercontent.com/15604894/32687017-d05c658c-c677-11e7-99fe-613ef145fcd2.png)

大写啊，你看错了吧

**Comment by iiiyu** [comment]
我的锅。 关闭了
