### ISSUE TITLE
请问在Linux下可以使用吗？我运行了一下出现如下问题，还望指教

### ISSUE THREAD

**Issue by geekmc** [Chyroc/WechatSogou#16]
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from wechatsogou.tools import *
  File "/root/WechatSogou/wechatsogou/**init**.py", line 4, in <module>
    from .db import mysql
  File "/root/WechatSogou/wechatsogou/db.py", line 3, in <module>
    import pymysql
ImportError: No module named pymysql

**Comment by leo-yi** [comment]
python运行提示No module xxxxx

基本可以用pip install xxxxx来解决

建议楼上先了解python基础，或者多用搜索引擎可解决
