### ISSUE TITLE
非常奇怪的错误, 说是wechartsogou没有"WechatSougouAPI"这个属性

### ISSUE THREAD

**Issue by ch812248495** [Chyroc/WechatSogou#187]
这是测试代码
import wechatsogou
api = wechatsogou.WechatSogouAPI()
print(api.search_gzh('新华社'))
这是报错信息:
Traceback (most recent call last):
  File "/Users/ch/PycharmProjects/crawller/crawller.py", line 1, in <module>
    import wechatsogou
  File "/Users/ch/PycharmProjects/crawller/venv/lib/python3.5/site-packages/wechatsogou/__init__.py", line 16, in <module>
    from wechatsogou.api import WechatSogouAPI
  File "/Users/ch/PycharmProjects/crawller/venv/lib/python3.5/site-packages/wechatsogou/api.py", line 9, in <module>
    import requests
  File "/Users/ch/PycharmProjects/crawller/venv/lib/python3.5/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Users/ch/PycharmProjects/crawller/venv/lib/python3.5/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/Users/ch/PycharmProjects/crawller/venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/Users/ch/PycharmProjects/crawller/venv/lib/python3.5/site-packages/urllib3/connection.py", line 2, in <module>
    ws_api =wechatsogou.WechatSogouAPI()
AttributeError: module 'wechatsogou' has no attribute 'WechatSogouAPI'
实在太奇怪了, 能帮忙分析下吗?

**Comment by Chyroc** [comment]
`pip install -U wechatsogou` 试试？

**Comment by ch812248495** [comment]
还是不行,好奇怪的错误,包应该是安装成功了, WechatSogouAPI 这个接口也能自动补全,就是会报这种奇怪的错误

**Comment by Chyroc** [comment]
看一下你装的环境和运行的环境是不是不一样

你运行的环境是`/Users/ch/PycharmProjects/crawller/venv/lib/python3.5`

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video

**Comment by FreeEye** [comment]
同求这个问题的解决方案，请问楼主解决了吗，是不是WeChatsogou被封了呢？
