### ISSUE TITLE
WechatSogouVcodeOcrException code -6 的问题

### ISSUE THREAD

**Issue by zjingchuan** [Chyroc/WechatSogou#196]
运行一段时间之后就会报这个错误，应该是微信服务器的验证码限制了。不知道怎么解决。更换ip也不行，过一段时间之后就好了。
```
39.108.132.15 - - [24/Apr/2018 16:21:30] "GET /get_gzh_article_by_history/HR%E8%BD%AC%E5%9E%8B%E7%AA%81%E7%A0%B4 HTTP/1.1" 500 -
Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)

  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)

  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)

  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value

  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()

  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)

  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)

  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value

  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()

  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)

  File "/usr/local/fastread/xunfeikuaiduServer.py", line 72, in get_gzh_info
    identify_image_callback_weixin=identify_image_callback_ruokuai_weixin)

  File "/usr/local/lib/python3.5/dist-packages/wechatsogou/api.py", line 339, in get_gzh_article_by_history
    identify_image_callback=identify_image_callback_weixin)

  File "/usr/local/lib/python3.5/dist-packages/wechatsogou/api.py", line 114, in __get_by_unlock
    raise WechatSogouVcodeOcrException(e)

wechatsogou.exceptions.WechatSogouVcodeOcrException: [WechatSogouAPI identify image] code: -6, msg: , cookie_count: 0
```

**Comment by Chyroc** [comment]
使用代理，然后出现-6，就更换代理？

**Comment by MiderWong** [comment]
-6的确是因为IP被限制了，输入验证码之后会返回-6的错误，中文提示就是：系统繁忙，40分钟左右自动解除限制。

**Comment by cuihom** [comment]
请问，有啥方法可以解决吗，用ip代理好像也不行的

**Comment by MiderWong** [comment]
@cuihom 代理IP+验证码识别机制，此模式已经投入商业应用并稳定运行2年以上
