### ISSUE TITLE
ImportError: cannot import name '_imaging' from 'PIL' (D:\Python3\lib\site-packages\PIL\__init__.py)

### ISSUE THREAD

**Issue by imslpxy** [Chyroc/WechatSogou#209]
import wechatsogou
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    import wechatsogou
  File "D:\Python3\lib\site-packages\wechatsogou\__init__.py", line 16, in <module>
    from wechatsogou.api import WechatSogouAPI
  File "D:\Python3\lib\site-packages\wechatsogou\api.py", line 13, in <module>
    from wechatsogou.five import quote
  File "D:\Python3\lib\site-packages\wechatsogou\five.py", line 3, in <module>
    from PIL import Image
  File "D:\Python3\lib\site-packages\PIL\Image.py", line 60, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (D:\Python3\lib\site-packages\PIL\__init__.py)

python版本3.7

**Comment by Sandychuang** [comment]
cannot import name 'py3'
python 3.6
