### ISSUE TITLE
安装时提示找不到lxml下的文件？

### ISSUE THREAD

**Issue by kjxy** [Chyroc/WechatSogou#216]
`C:\Users\Administrator>pip install wechatsogou --upgrade
Collecting wechatsogou
  Using cached https://files.pythonhosted.org/packages/62/46/d982d0e8bdd290fba5ef6390ad238d4206cd61256f24d2cb8c68d88efa09/wechatsogou-4.3.0-py2.py3-none-any.whl
Requirement already up-to-date: Werkzeug in d:\programdata\anaconda3\lib\site-packages (from wechatsogou)
Requirement already up-to-date: bs4 in d:\programdata\anaconda3\lib\site-packages (from wechatsogou)
Collecting lxml (from wechatsogou)
  Using cached https://files.pythonhosted.org/packages/b9/55/bcc78c70e8ba30f51b5495eb0e3e949aa06e4a2de55b3de53dc9fa9653fa/lxml-4.2.5-cp36-cp36m-win_amd64.whl
Requirement already up-to-date: xlrd in d:\programdata\anaconda3\lib\site-packages (from wechatsogou)
Requirement already up-to-date: requests in d:\programdata\anaconda3\lib\site-packages (from wechatsogou)
Requirement already up-to-date: six in d:\programdata\anaconda3\lib\site-packages (from wechatsogou)
Requirement already up-to-date: future in d:\programdata\anaconda3\lib\site-packages (from wechatsogou)
Requirement already up-to-date: Pillow in d:\programdata\anaconda3\lib\site-packages (from wechatsogou)
Collecting beautifulsoup4 (from bs4->wechatsogou)
  Using cached https://files.pythonhosted.org/packages/21/0a/47fdf541c97fd9b6a610cb5fd518175308a7cc60569962e776ac52420387/beautifulsoup4-4.6.3-py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->wechatsogou)
  Using cached https://files.pythonhosted.org/packages/56/9d/1d02dd80bc4cd955f98980f28c5ee2200e1209292d5f9e9cc8d030d18655/certifi-2018.10.15-py2.py3-none-any.whl
Requirement already up-to-date: idna<2.8,>=2.5 in d:\programdata\anaconda3\lib\site-packages (from requests->wechatsogou)
Requirement already up-to-date: urllib3<1.24,>=1.21.1 in d:\programdata\anaconda3\lib\site-packages (from requests->wechatsogou)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in d:\programdata\anaconda3\lib\site-packages (from requests->wechatsogou)
Installing collected packages: lxml, wechatsogou, beautifulsoup4, certifi
  Found existing installation: lxml 3.7.2
Exception:
Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "d:\ProgramData\Anaconda3\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "d:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "d:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_install.py", line 694, in uninstall
    for path in pip.wheel.uninstallation_paths(dist):
  File "d:\ProgramData\Anaconda3\lib\site-packages\pip\wheel.py", line 534, in unique
    for item in fn(*args, **kw):
  File "d:\ProgramData\Anaconda3\lib\site-packages\pip\wheel.py", line 553, in uninstallation_paths
    r = csv.reader(FakeFile(dist.get_metadata_lines('RECORD')))
  File "d:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1490, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "d:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1486, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "d:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1595, in _get
    with open(path, 'rb') as stream:
**FileNotFoundError: [Errno 2] No such file or directory: 'd:\\programdata\\anaconda3\\lib\\site-packages\\lxml-3.7.2.dist-info\\RECORD**'`
最后一句报错，No such file or directory: 'd:\\programdata\\anaconda3\\lib\\site-packages\\lxml-3.7.2.dist-info\\RECORD 我又重新安装了lxml，但是还是不行...

**Comment by kjxy** [comment]
已解决：
随意打开此项目的一个py文件，PyCharm会提示相关包更新，更新完成之后，再pip install wechatsogou
