### ISSUE TITLE
输入验证码后程序出错

### ISSUE THREAD

**Issue by zhxxmu** [Chyroc/WechatSogou#227]
错误代码如下，请教是什么问题？

Traceback (most recent call last):
  File "H:\Anaconda\lib\site-packages\wechatsogou\api.py", line 115, in __get_by_unlock
    unlock_platform(url, resp, session, unlock_callback, identify_image_callback)
  File "H:\Anaconda\lib\site-packages\wechatsogou\api.py", line 82, in __unlock_sogou
    msg=r_unlock.get('msg')))
wechatsogou.exceptions.WechatSogouVcodeOcrException: [WechatSogouAPI identify image] code: 3, msg: éªè¯ç è¾å¥éè¯¯, è¯·éæ°è¾å¥ï¼

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "getwechatarticles.py", line 6, in <module>
    dictArticles = ws_api.get_gzh_article_by_history('厦门市图书馆')
  File "H:\Anaconda\lib\site-packages\wechatsogou\api.py", line 370, in get_gzh_article_by_history
    gzh_list = self.get_gzh_info(keyword, unlock_callback_sogou, identify_image_callback_sogou)
  File "H:\Anaconda\lib\site-packages\wechatsogou\api.py", line 192, in get_gzh_info
    info = self.search_gzh(wecgat_id_or_name, 1, unlock_callback, identify_image_callback)
  File "H:\Anaconda\lib\site-packages\wechatsogou\api.py", line 239, in search_gzh
    identify_image_callback=identify_image_callback)
  File "H:\Anaconda\lib\site-packages\wechatsogou\api.py", line 119, in __get_by_unlock
    raise WechatSogouVcodeOcrException(e)
wechatsogou.exceptions.WechatSogouVcodeOcrException: [WechatSogouAPI identify image] code: 3, msg: éªè¯ç è¾å¥éè¯¯, è¯·éæ°è¾å¥ï¼

**Comment by s277645013** [comment]
我也遇到了这个问题

**Comment by s277645013** [comment]
总感觉是触发了反爬策略，是爬了一会以后，前几次输入验证码都正确识别，之后才报错的，你加上编码后就没再报过错了吗，你的爬取时间间隔是多长时间啊

**Comment by zhxxmu** [comment]
我爬取频率很低，3小时一次，只是针对一个微信号而已。目前加上编码后，没有再报错。还有待观察。

**Comment by Chyroc** [comment]
https://github.com/Chyroc/WechatSogou/issues/235
