### ISSUE TITLE
类型错误！NoneType object is not iterable

### ISSUE THREAD

**Issue by tangeven** [Chyroc/WechatSogou#233]
Traceback (most recent call last):
  File "D:/dem0_spider/article_collector.py", line 73, in <module>
    articles = get_articles(timedel=1)
  File "D:/dem0_spider/article_collector.py", line 27, in get_articles
    articles.extend(reformat(ws_api.get_gzh_article_by_history(account)))
TypeError: 'NoneType' object is not iterable

**Comment by IKkSssDendi** [comment]
搜狗更新了反爬策略，会检测ua，所以需要构造ua。要不然爬取返回为空。你看看是不是这个问题

**Comment by Chyroc** [comment]
https://github.com/Chyroc/WechatSogou/issues/235
