### ISSUE TITLE
请问最近搜狗返回的Html内容是改了吗？最近抓内容出错。

### ISSUE THREAD

**Issue by william2177** [Chyroc/WechatSogou#25]
Traceback (most recent call last):
  File "wechat_crawling.py", line 98, in <module>
    messages = wechat_api.get_gzh_message(wechatid=wid)
  File "./sogouapi/wechatsogou\api.py", line 203, in get_gzh_message
    gzh_info = self.get_gzh_info(wechatid)
  File "./sogouapi/wechatsogou\api.py", line 111, in get_gzh_info
    info = self.search_gzh_info(wechatid, 1)
  File "./sogouapi/wechatsogou\api.py", line 67, in search_gzh_info
    wechatid.append(cache_re[1])
IndexError: list index out of range
===============分割线==========================
如上是错误内容。我看了一下，api.py的search_gzh_info开始试图获取内容，其中
cache_re = re.split(u'微信号：|功能介绍：|认证：|最近文章：', cache_list[0])
这边拿到的split内容最后的结果（包括一开始的cache变量读到的内容）只有如下这样：
“安信电力设备新能源微信号:anxin_new_energy月发文1篇    平均阅读88”

不知道是什么原因导致的。。。求看看！谢谢

**Comment by Chyroc** [comment]
@william2177 你更新下，已经修复了

**Comment by william2177** [comment]
这个问题解决了，但是出现了类似的如下错误：
Traceback (most recent call last):
  File "wechat_crawling.py", line 98, in <module>
    messages = wechat_api.get_gzh_message(wechatid=wid)
  File "./WechatSogou/wechatsogou\api.py", line 188, in get_gzh_message
    gzh_info = self.get_gzh_info(wechatid)
  File "./WechatSogou/wechatsogou\api.py", line 96, in get_gzh_info
    info = self.search_gzh_info(wechatid, 1)
  File "./WechatSogou/wechatsogou\api.py", line 74, in search_gzh_info
    'renzhen': renzhen[0]
IndexError: list index out of range

**Comment by Chyroc** [comment]
@william2177 已修复
