### ISSUE TITLE
获取历史信息报错

### ISSUE THREAD

**Issue by isaac-cat** [Chyroc/WechatSogou#258]
ws_api.get_gzh_article_by_history('运动科学论坛')
报错信息：

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\python\wechatsogou\venv\lib\site-packages\wechatsogou\api.py", line 433, in get_gzh_article_by_history
    requests error
  File "D:\python\wechatsogou\venv\lib\site-packages\wechatsogou\api.py", line 236, in get_gzh_info
    """
  File "D:\python\wechatsogou\venv\lib\site-packages\wechatsogou\api.py", line 292, in search_gzh
    gzh_list = WechatSogouStructuring.get_gzh_by_search(resp.text)
  File "D:\python\wechatsogou\venv\lib\site-packages\wechatsogou\api.py", line 193, in __format_url
    unlock_platform=self.__unlock_sogou,
  File "D:\python\wechatsogou\venv\lib\site-packages\wechatsogou\api.py", line 118, in __get_by_unlock
    if 'antispider' in resp.url or '请输入验证码' in resp.text:
  File "D:\python\wechatsogou\venv\lib\site-packages\wechatsogou\api.py", line 77, in __unlock_sogou
    'Referer': url,
wechatsogou.exceptions.WechatSogouRequestsException: ('WechatSogouAPI get img', <Response [200]>)

python版本：3.7
ide：pycharm
wechatsogou: 4.5.4

**Comment by unraval** [comment]
我也是这种情况，不知道咋处理

**Comment by isaac-cat** [comment]
> 我也是这种情况，不知道咋处理

现在不报错，然而返回数据为空

**Comment by crisis111** [comment]
我也是这么情况 ，报错信息都一模一样。。。。

**Comment by lixindou2018** [comment]
runfile('F:/reptile/wechat/WechatSogou-master/wechatsogou/PaChong.py', wdir='F:/reptile/wechat/WechatSogou-master/wechatsogou')
Reloaded modules: wechatsogou.request, wechatsogou.exceptions, wechatsogou.tools, wechatsogou.structuring, wechatsogou.filecache, wechatsogou, wechatsogou.api, wechatsogou.identify_image, wechatsogou.const, wechatsogou.five

不报错返回信息为空？？？？？
