### ISSUE TITLE
get_gzh_article_by_hot (Not working)

### ISSUE THREAD

**Issue by tczee36** [chyroc/WechatSogou#296]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wechatsogou/api.py", line 489, in get_gzh_article_by_hot
    return WechatSogouStructuring.get_gzh_article_by_hot(resp.text)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wechatsogou/structuring.py", line 422, in get_gzh_article_by_hot
    send_time = int(send_time[0])
IndexError: list index out of range

see above

**Comment by kimmykuang** [comment]
me  too

**Comment by Human0203** [comment]
I have test and it shows return 0 result so this message occur
