### ISSUE TITLE
ModuleNotFoundError: No module named 'werkzeug.contrib'

### ISSUE THREAD

**Issue by fanhoodrex** [chyroc/WechatSogou#298]
按照文档执行`import wechatsogou`后，命令行出现以下的错误
```
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import wechatsogou
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Zacha\AppData\Local\Programs\Python\Python38-32\lib\site-packages\wechatsogou\__init__.py", line 16, in <module>
    from wechatsogou.api import WechatSogouAPI
  File "C:\Users\Zacha\AppData\Local\Programs\Python\Python38-32\lib\site-packages\wechatsogou\api.py", line 16, in <module>
    from wechatsogou.identify_image import (identify_image_callback_by_hand, unlock_sogou_callback_example, unlock_weixin_callback_example, ws_cache)
  File "C:\Users\Zacha\AppData\Local\Programs\Python\Python38-32\lib\site-packages\wechatsogou\identify_image.py", line 10, in <module>
    from wechatsogou.filecache import WechatCache
  File "C:\Users\Zacha\AppData\Local\Programs\Python\Python38-32\lib\site-packages\wechatsogou\filecache.py", line 3, in <module>
    from werkzeug.contrib.cache import FileSystemCache
ModuleNotFoundError: No module named 'werkzeug.contrib'
```
**是我安装的方式不对还是我的本地的缺了什么文件或者第三方库吗？**

**Comment by ay1Jin** [comment]
看项目栏中的requirements.txt的依赖包，然后一个一个自己装，装完后pip install wechatsogou即可。

**Comment by MartinForReal** [comment]
related issue: https://github.com/Azure-Samples/ms-identity-python-webapp/issues/16

**Comment by longjxchina** [comment]
> 看项目栏中的requirements.txt的依赖包，然后一个一个自己装，装完后pip install wechatsogou即可。

pip install -r requirements.txt时出错：
ERROR: astroid 2.3.3 has requirement six~=1.12, but you'll have six 1.10.0 which is incompatible.
请问怎么解决呢？

**Comment by longjxchina** [comment]
> 按照文档执行`import wechatsogou`后，命令行出现以下的错误
> 
> ```
> Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import wechatsogou
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\Zacha\AppData\Local\Programs\Python\Python38-32\lib\site-packages\wechatsogou\__init__.py", line 16, in <module>
>     from wechatsogou.api import WechatSogouAPI
>   File "C:\Users\Zacha\AppData\Local\Programs\Python\Python38-32\lib\site-packages\wechatsogou\api.py", line 16, in <module>
>     from wechatsogou.identify_image import (identify_image_callback_by_hand, unlock_sogou_callback_example, unlock_weixin_callback_example, ws_cache)
>   File "C:\Users\Zacha\AppData\Local\Programs\Python\Python38-32\lib\site-packages\wechatsogou\identify_image.py", line 10, in <module>
>     from wechatsogou.filecache import WechatCache
>   File "C:\Users\Zacha\AppData\Local\Programs\Python\Python38-32\lib\site-packages\wechatsogou\filecache.py", line 3, in <module>
>     from werkzeug.contrib.cache import FileSystemCache
> ModuleNotFoundError: No module named 'werkzeug.contrib'
> ```
> 
> _是我安装的方式不对还是我的本地的缺了什么文件或者第三方库吗？这个**werkzeug.contrib**又是什么呢？_

安装这个即可解决：
pip install Werkzeug==0.14.1，先使用这个版本的试试，我没用最新的版本
