### ISSUE TITLE
[Bug report]有依赖损坏

### ISSUE THREAD

**Issue by BeautyYuYanli** [chyroc/WechatSogou#309]
```
>>> import wechatsogou
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/beaut/.local/lib/python3.8/site-packages/wechatsogou/__init__.py", line 16, in <module>
    from wechatsogou.api import WechatSogouAPI
  File "/home/beaut/.local/lib/python3.8/site-packages/wechatsogou/api.py", line 16, in <module>
    from wechatsogou.identify_image import (identify_image_callback_by_hand, unlock_sogou_callback_example, unlock_weixin_callback_example, ws_cache)
  File "/home/beaut/.local/lib/python3.8/site-packages/wechatsogou/identify_image.py", line 10, in <module>
    from wechatsogou.filecache import WechatCache
  File "/home/beaut/.local/lib/python3.8/site-packages/wechatsogou/filecache.py", line 3, in <module>
    from werkzeug.contrib.cache import FileSystemCache
ModuleNotFoundError: No module named 'werkzeug.contrib'
```
`werkzeug`库可能已发生变化

**Comment by legend-zl** [comment]
你可以看这篇文章解决：https://blog.csdn.net/qq_26373925/article/details/108045684
