### ISSUE TITLE
输入验证码后报错

### ISSUE THREAD

**Issue by Qmoliang** [Chyroc/WechatSogou#32]
Traceback (most recent call last):
  File "E:\Python27\lib\logging\handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "E:\Python27\lib\logging\handlers.py", line 156, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "E:\Python27\lib\logging\__init__.py", line 734, in format
    return fmt.format(record)
  File "E:\Python27\lib\logging\__init__.py", line 465, in format
    record.message = record.getMessage()
  File "E:\Python27\lib\logging\__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file basic.py, line 160

**Comment by Chyroc** [comment]
https://github.com/Chyroc/WechatSogou/pull/92
