### ISSUE TITLE
python3.8 安装完包执行报错

### ISSUE THREAD

**Issue by science09** [Chyroc/WechatSogou#327]
Traceback (most recent call last):
  File "/Users/user/PycharmProjects/py_auto/test.py", line 5, in <module>
    import wechatsogou
  File "/Users/user/PycharmProjects/py_auto/venv/lib/python3.8/site-packages/wechatsogou/__init__.py", line 16, in <module>
    from wechatsogou.api import WechatSogouAPI
  File "/Users/user/PycharmProjects/py_auto/venv/lib/python3.8/site-packages/wechatsogou/api.py", line 16, in <module>
    from wechatsogou.identify_image import (identify_image_callback_by_hand, unlock_sogou_callback_example, unlock_weixin_callback_example, ws_cache)
  File "/Users/user/PycharmProjects/py_auto/venv/lib/python3.8/site-packages/wechatsogou/identify_image.py", line 10, in <module>
    from wechatsogou.filecache import WechatCache
  File "/Users/user/PycharmProjects/py_auto/venv/lib/python3.8/site-packages/wechatsogou/filecache.py", line 3, in <module>
    from werkzeug.contrib.cache import FileSystemCache
ModuleNotFoundError: No module named 'werkzeug.contrib'

**Comment by Pandolar** [comment]
不支持3.8吧    3.6 3.7 应该可以

**Comment by GodL9211** [comment]
我也是3.8报这个错
