### ISSUE TITLE
 ImportError: cannot import name config

### ISSUE THREAD

**Issue by panw3i** [Chyroc/WechatSogou#40]

**Comment by Chyroc** [comment]
错误代码呢。

**Comment by panw3i** [comment]
roo ~# pip install wechatsogou
Downloading/unpacking wechatsogou
  Downloading wechatsogou-2.0.3.tar.gz
  Running setup.py (path:/tmp/pip_build_root/wechatsogou/setup.py) egg_info for package wechatsogou
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/wechatsogou/setup.py", line 6, in <module>
        import wechatsogou
      File "wechatsogou/__init__.py", line 3, in <module>
        from .api import WechatSogouApi
      File "wechatsogou/api.py", line 9, in <module>
        from .basic import WechatSogouBasic
      File "wechatsogou/basic.py", line 51, in <module>
        from .filecache import WechatCache
      File "wechatsogou/filecache.py", line 3, in <module>
        from werkzeug.contrib.cache import FileSystemCache
    ImportError: No module named werkzeug.contrib.cache
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/wechatsogou/setup.py", line 6, in <module>

    import wechatsogou

  File "wechatsogou/__init__.py", line 3, in <module>

    from .api import WechatSogouApi

  File "wechatsogou/api.py", line 9, in <module>

    from .basic import WechatSogouBasic

  File "wechatsogou/basic.py", line 51, in <module>

    from .filecache import WechatCache

  File "wechatsogou/filecache.py", line 3, in <module>

    from werkzeug.contrib.cache import FileSystemCache

ImportError: No module named werkzeug.contrib.cache

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/wechatsogou
Storing debug log for failure in /root/.pip/pip.log

**Comment by panw3i** [comment]
已解决，感谢

**Comment by qianggu** [comment]
我也遇到这个问题，怎么解决的？

**Comment by halfblood369** [comment]
同上，如何解决哦？

**Comment by segatecm** [comment]
pip install werkzeug
