### ISSUE TITLE
请问logging.config.fileConfig('logging.conf')出错如何解决

### ISSUE THREAD

**Issue by PureBinaryHeart** [Chyroc/WechatSogou#60]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 540, in runfile
    execfile(filename, namespace)
  File "/home/crd/桌面/python/untitled1.py", line 24, in <module>
    logging.config.fileConfig('logging.conf')
  File "/usr/lib/python2.7/logging/config.py", line 77, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/lib/python2.7/logging/config.py", line 113, in _create_formatters
    flist = cp.get("formatters", "keys")
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'formatters'
日志出错？

**Comment by Chyroc** [comment]
看看你的untitled1.py

**Comment by maxmhshi** [comment]
应该是找不到logging.conf文件，你可以把这个文件放到你的执行目录下面
https://github.com/Chyroc/WechatSogou/blob/master/logging.conf

**Comment by Chyroc** [comment]
https://github.com/Chyroc/WechatSogou/pull/96
