### ISSUE TITLE
deal_article_comment(text=text)并不能获得用户的评论内容

### ISSUE THREAD

**Issue by lyhshzu** [Chyroc/WechatSogou#8]
执行article_info = wechats.deal_article(url)时，出现如下错误：
Traceback (most recent call last):
  File "F:/wechat/WechatSogou-master/tt.py", line 11, in <module>
    article_info = wechats.deal_article(url)
  File "F:/wechat/WechatSogou-master\wechatsogou\api.py", line 362, in deal_article
    comment = self.deal_article_comment(url=url)
  File "F:/wechat/WechatSogou-master\wechatsogou\api.py", line 316, in deal_article_comment
    sg_data = '{' + sg_data[0].replace(u'\r\n', '').replace(' ', '') + '}'
IndexError: list index out of range
出错的原因是并未获得评论相关内容，需要什么设置或改变才能获得，求帮助，谢谢！

**Comment by Chyroc** [comment]
必须是临时的文章链接才可以获取评论

**Comment by lyhshzu** [comment]
谢谢及时回复，有没有办法获得公众号的某个消息的评论内容呢

**Comment by Chyroc** [comment]
@lyhshzu 只要是临时链接，评论数据都可以获取。否则就不行。
